-- noinspection SqlNoDataSourceInspectionForFile

-- this table will be autogenerated by hibernate since we use drop-and-create
-- https://quarkus.io/blog/hibernate-orm-config-profiles/
-- create table users (
--     id serial primary key,
--     username varchar(255),
--     email varchar(255)
-- );

insert into users (username, email) values
('teedjay', 'teedjay@somewhere.no'),
('ola', 'ola@somewhere.no'),
('bola', 'bola@somewhere.no');
