package com.teedjay;

import org.eclipse.microprofile.openapi.annotations.tags.Tag;
import org.jboss.resteasy.annotations.jaxrs.PathParam;

import javax.transaction.Transactional;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import java.util.List;

@Path("/users")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@Tag(name = "users", description = "Repository for CRUD of users")
public class UsersResource {

    @GET
    public List<Users> getAllUsers() {
        return Users.listAll();
    }

    @GET
    @Path("{id}")
    public Users getAllUsers(@PathParam Integer id) {
        return Users.findById(id);
    }

    @POST
    @Transactional
    public Users createUser(Users users) {
        if (users.id != null) throw new BadRequestException("ID is autogenerated, make sure to not pass any value when creating entities.");
        users.persist();
        return users;
    }

}
